### ISSUE TITLE
[🐛] Customization: Having a single quote in the name of application breaks the profile page

### ISSUE THREAD

**Issue by nakami** [juice-shop/juice-shop#1726] opened 2021-11-12 18:35 UTC
# :bug: Bug report

## Description

If you choose a name with single quotes as the name of your application in the config file, it breaks the profile page. It might also break different pages, but the profile page was the only one I could make out so far.

e.g.
```yaml
# myconfig.yml
# ...
application:
  domain: juice-sh.op
  name: "nakami's Juice Shop"
# ...
```

### Is this a regression?

I don't think so, seems like a oversight in design.

## :microscope: Minimal Reproduction

1. Save this config in the config directory:  [myconfig.yml.txt](https://github.com/juice-shop/juice-shop/files/7529628/myconfig.yml.txt) (duplicate of `default.yml` with `"nakami's Juice Shop"` as application->name)
2. Be sure to set the `NODE_ENV` var to `myconfig` to use this config
3. Run `npm install` and `npm start`
4. Create a new user and log in, e.g. a.b@c.com:aaaaa
5. Navigate to the profile: On the top right, click on "Account" and then on the first field (which says your email) or directly go to [http://localhost:3000/profile](http://localhost:3000/profile)
6. Get a 500 Error page

## :fire: Exception or Error

<pre><code>
nakami's Juice Shop (Express ^4.17.1)
500 Error: Pug:82:51
   80|                             label.mdl-textfield__label(for='username', style='color: #FFFFFF;') Username:
   81|                      button(id='submit', type='submit', style='background-color:#546E7A; color: #FFFFFF; margin-top: -10px; text-transform: capitalize;', aria-label='Button to save/set the username').mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect Set Username
 > 82|                      p(style='margin-bottom:10%;')
----------------------------------------------------------^
The end of the string reached with no closing bracket ) found.
   at makeError (PATH\TO\REPO\github-juice-shop\node_modules\pug-error\index.js:34:13)
   at Lexer.error (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:62:15)
   at Lexer.bracketExpression (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:274:14)
   at Lexer.attrs (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:1445:24)
   at Lexer.callLexerFunction (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:1647:23)
   at Lexer.advance (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:1686:12)
   at Lexer.callLexerFunction (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:1647:23)
   at Lexer.getTokens (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:1706:12)
   at lex (PATH\TO\REPO\github-juice-shop\node_modules\pug-lexer\index.js:12:42)
   at Object.lex (PATH\TO\REPO\github-juice-shop\node_modules\pug\lib\index.js:104:9)
   at Function.loadString [as string] (PATH\TO\REPO\github-juice-shop\node_modules\pug-load\index.js:53:24)
   at compileBody (PATH\TO\REPO\github-juice-shop\node_modules\pug\lib\index.js:82:18)
   at Object.exports.compile (PATH\TO\REPO\github-juice-shop\node_modules\pug\lib\index.js:269:16)
   at PATH\TO\REPO\github-juice-shop\build\routes\userProfile.js:49:36
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
v14.17.2 # node
7.21.1   # npm

</code></pre>

**Comment by bkimminich** [comment] 2021-11-12 19:28
Nice find! I'd hope this doesn't  affect any screens other than the legacy ones built with Pug templates. Will test and see where the issue is originating from.

**Comment by bkimminich** [comment] 2021-11-13 19:18
Ok, it's really a classic injection in the Pug templates. The config values are put into the template before the template it compiled, so `'` will mess up the template. Other character probably do the same. I'll try to find some Pug-friendly encoder to safely set the application name.

**Comment by bkimminich** [comment] 2021-11-13 19:37
With the `develop` branch version or `snapshot` Docker image this issue should be fixed now.

**Closed as completed by bkimminich** 2021-11-13 19:37 UTC
Labels: bug, customization
