### ISSUE TITLE
Customer Feedback error

### ISSUE THREAD

**Issue by fjodor81** [juice-shop/juice-shop#233] opened 2016-11-24 09:45 UTC
Customer feedback is not displayed.

The Customer feedback disappeared after I tried to REST POST a review. I think I used the following raw body:
`{"comment":"Really bad shop!","rating":0,"createdAt":"2016-11-24T06:08:46.000Z","updatedAt":"2016-11-24T06:08:46.000Z","UserId":2`

**Error from console:**
TypeError: Cannot read property 'slide' of undefined
    at p.select.a.select [as select] (http://localhost:3000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:9921)
    at m.p.next.a.next [as next] (http://localhost:3000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:9430)
    at fn (eval at <anonymous> (http://localhost:3000/bower_components/angular/angular.min.js:233:35), <anonymous>:2:203)
    at b (http://localhost:3000/bower_components/angular/angular.min.js:126:128)
    at e (http://localhost:3000/bower_components/angular/angular.min.js:276:195)
    at m.$eval (http://localhost:3000/bower_components/angular/angular.min.js:145:347)
    at m.$apply (http://localhost:3000/bower_components/angular/angular.min.js:146:52)
    at HTMLAnchorElement.<anonymous> (http://localhost:3000/bower_components/angular/angular.min.js:276:247)
    at HTMLAnchorElement.n.event.dispatch (http://localhost:3000/bower_components/jquery/dist/jquery.min.js:3:6466)
    at HTMLAnchorElement.r.handle (http://localhost:3000/bower_components/jquery/dist/jquery.min.js:3:3241)

**Comment by bkimminich** [comment] 2016-11-24 20:52
Just reproduced your POST and it created a new Feedback in the database with `undefined` for `comment`, `rating` and `UserId` but interestingly, the carousel on the `/#/about` page still works fine in Chrome and Firefox:

![image](https://cloud.githubusercontent.com/assets/3531020/20609607/18ab9b8a-b28f-11e6-84f2-bb0073c1e0ad.png)

I suppose it is a hidden array index that went out of bounds, as this is the only access to a `.slide` property happening in `ui-bootstrap-tpls`. If you can reproduce exactly how this error happened I can look into it further.

**Comment by bkimminich** [comment] 2016-11-25 08:52
Also just tested the same payload but with closing `}` and it still works. Must really have been something else that caused the slides array to go undefined.

**Comment by bkimminich** [comment] 2016-12-05 15:05
I'm closing this issue because I honestly cannot reproduct the behavior. Please feel free to reopen if this occurs again.

**Comment by bkimminich** [comment] 2017-01-02 15:53
The error can be reproduced with the following steps:

1. `npm start`
2. Visit _About Us_ :arrow_right: All Feedback is visible in the carousel widget
3. Log in as anyone
4. Visit _Administration_ page
5. Delete any entry from _Customer Feedback_ using the trashcan button
6. Go back to _About Us_ :arrow_right: Carousel is now broken and error appears periodically in console:

```
TypeError: Cannot read property 'slide' of undefined
    at Object.p.select.a.select (ui-bootstrap-tpls.min.js:7)
    at m.p.next.a.next (ui-bootstrap-tpls.min.js:7)
    at fn (eval at compile (angular.min.js:1), <anonymous>:4:203)
    at b (angular.js:16123)
    at e (angular.js:26490)
    at m.$eval (angular.js:17913)
    at m.$apply (angular.js:18013)
    at HTMLAnchorElement.<anonymous> (angular.js:26495)
    at HTMLAnchorElement.dispatch (jquery.js:4435)
    at HTMLAnchorElement.r.handle (jquery.js:4121)
```

Sidenote: Neither `F5` nor `Strg-F5` refresh mitigates this effect.

**Closed as completed** 2017-01-27 09:49 UTC
Labels: bug
